name: trivy-plugin-aqua release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        description: Tag version

jobs:
  build:
    name: releasing trivy-plugin-aqua
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - uses: actions/setup-go@v3
      #   with:
      #     stable: "false"
      #     go-version: "1.18"
      # - run: go version

      # - name: Release
      #   uses: goreleaser/goreleaser-action@v3
      #   with:
      #     version: latest
      #     args: release --rm-dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: "Set chosen tag"
        env:
          TAG: ${{ github.event.inputs.tag || steps.previoustag.outputs.tag }}
        run: |
          echo "tag=${COMMIT_VAR}" >> $GITHUB_ENV

      - name: Update plugin Links
        run: |
          sed  -e "s/PLACEHOLDERVERSION/${{ env.tag }}/g" .github/plugin_template.yaml > plugin.yaml

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PR_CREATION_TOKEN }}
          branch: "update-plugin-links-${{ env.tag }}"
          title: "Update Plugin Artifacts Links for ${{ env.tag }}"
          delete-branch: true
          base: master
          add-paths: |
            plugin.yaml
      # - name: Send Slack message (Workflow)
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.21.0
      #   with:
      #     payload: |
      #       {
      #         "link": "${{ steps.cpr.outputs.pull-request-url }}"
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.CODE_TEAM_SLACK_WEBHOOK }}
