name: Act on release created

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    environment: dev_environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - run: echo $GITHUB_ENV
      # - run: echo $GITHUB_REF
      # - run: echo $GITHUB_REF_NAME
      # - name: Set env
      #   run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # - name: Test
      #   run: |
      #     echo $RELEASE_VERSION
      #     echo ${{ env.RELEASE_VERSION }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PRIVATE_REPO }}
          branch: "update-plugin-links-${{github.ref_name}}"
          title: "Update Plugin Artifacts Links for ${{github.ref_name}}"
          delete-branch: true
          base: main
          add-paths: |
            plugin.yaml
      # - name: Send Slack message (Workflow)
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.21.0
      #   with:
      #     payload: |
      #       {
      #         "link": "${{ steps.cpr.outputs.pull-request-url }}"
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.CODE_TEAM_SLACK_WEBHOOK }}